services:
    alfredoramos.mailrelay.cron.task.mailrelay_user_sync:
        class: alfredoramos\mailrelay\cron\task\mailrelay_user_sync
        arguments:
            - '@alfredoramos.mailrelay.helper'
            - '@alfredoramos.mailrelay.mailrelay'
        calls:
            - [set_name, [cron.task.mailrelay_user_sync]]
        tags:
            - { name: cron.task }
